export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST'
export const GET_PIC_LIST = 'GET_PIC_LIST'
export const GET_JOKE_LIST = 'GET_JOKE_LIST'
export const GET_ENTERTAINMENT_LIST = 'GET_ENTERTAINMENT_LIST'
export const GET_SLIDERS = 'GET_SLIDERS'
export const SHOW_LOADING_MORE = 'SHOW_LOADING_MORE'



